### ISSUE TITLE
pymoogi display issue

### ISSUE THREAD

**Issue by wj198414** [madamow/pymoogi#1]
I installed pymoogi on an iMac. 

When I run: pymoogi synth_example.par

I got the following image popping up:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/12777678/70736480-6b7ea200-1cde-11ea-8a93-2b5ff9fff4c8.png">

but shouldn't there be lines of different colors? I notice this when I saw display from a PC with pymoogi installed.

**Comment by madamow** [comment]
You should start with checking out files. The lines of different colors, synthetic spectra to be exact,
are stored in out2 file (should be generated in example catalog). The file should look like this (I am pasting a fragment of it):

```
element Li:  abundance =  3.38
element C :  abundance =  7.86
element N :  abundance =  8.16
element O :  abundance =  8.42
Isotopic Ratio: [   3/   3.00060] =    100.000
Isotopic Ratio: [   3/   3.00070] =      1.000
Isotopic Ratio: [ 607/ 607.01214] =      1.000
Isotopic Ratio: [ 607/ 607.01314] =     20.000
MODEL:   5121./   2.97/  -0.27      mic = 1.0600             vt= 1.06 M/H=-0.27 
   6100.000   6105.000      0.020      5.000
 0.0003 0.0005 0.0010 0.0027 0.0136 0.0509 0.0818 0.0548 0.0150 0.0045
 0.0157 0.0519 0.1079 0.1523 0.1401 0.0741 0.0212 0.0107 0.0279 0.0341
 0.0141 0.0022 0.0005 0.0004 0.0008 0.0020 0.0054 0.0121 0.0220 0.0320
 0.0369 0.0338 0.0244 0.0142 0.0076 0.0044 0.0026 0.0024 0.0037 0.0041
 0.0028 0.0017 0.0015 0.0032 0.0081 0.0140 0.0153 0.0106 0.0047 0.0016
 0.0010 0.0012 0.0013 0.0011 0.0008 0.0008 0.0008 0.0006 0.0005 0.0005
 0.0008 0.0019 0.0032 0.0023 0.0009 0.0006 0.0007 0.0008 0.0013 0.0027
 0.0057 0.0085 0.0084 0.0056 0.0028 0.0015 0.0012 0.0010 0.0009 0.0009
 0.0009 0.0013 0.0023 0.0039 0.0051 0.0048 0.0034 0.0020 0.0014 0.0014
 0.0014 0.0016 0.0018 0.0022 0.0024 0.0033 0.0106 0.0357 0.0661 0.0625
 0.0316 0.0118 0.0074 0.0081 0.0132 0.0553 0.2729 0.5303 0.6187 0.6217
 0.5436 0.3010 0.0659 0.0158 0.0099 0.0085 0.0079 0.0079 0.0091 0.0166
 0.0441 0.0909 0.1151 0.0889 0.0456 0.0242 0.0224 0.0317 0.0666 0.1337
 0.1771 0.1734 0.2817 0.5823 0.7158 0.7756 0.7968 0.7855 0.7384 0.6370
 0.3671 0.1285 0.0689 0.0467 0.0349 0.0274 0.0222 0.0183 0.0155 0.0133
 0.0118 0.0106 0.0098 0.0095 0.0098 0.0137 0.0520 0.2354 0.4670 0.5516
 0.5259 0.3684 0.1743 0.2782 0.4330 0.4532 0.3334 0.1267 0.0254 0.0094
 0.0101 0.0170 0.0325 0.0587 0.0937 0.1310 0.1623 0.1841 0.1994 0.2164
 0.2395 0.2637 0.2775 0.2714 0.2415 0.1913 0.1317 0.0776 0.0391 0.0173
 0.0072 0.0032 0.0018 0.0014 0.0012 0.0010 0.0010 0.0009 0.0008 0.0008
 0.0008 0.0010 0.0020 0.0063 0.0170 0.0301 0.0342 0.0249 0.0119 0.0046
 0.0029 0.0030 0.0026 0.0018 0.0011 0.0009 0.0016 0.0029 0.0045 0.0054
 0.0048 0.0029 0.0013 0.0006 0.0004 0.0005 0.0008 0.0014 0.0022 0.0040
 0.0104 0.0236 0.0358 0.0348 0.0212 0.0079 0.0023 0.0056 0.0298 0.0545
 0.0332 0.0067 0.0008 0.0004 0.0004 0.0003 0.0003 0.0003 0.0003 0.0003
 0.0003
ALL abundances NOT listed below differ from solar by  -0.27 dex
```
If you have there nans, or **, or something similar it means that there is something not right with MOOG executable.

**Comment by wj198414** [comment]
I do not get anything like yours:

This is that I got. It looks like that MOOG is doing something funky. Any idea to start for tracking the issue?
ALL abundances NOT listed below differ from solar by  -0.27 dex
element Li:  abundance =  3.38
element C :  abundance =  7.86
element N :  abundance =  8.16
element O :  abundance =  8.42
Isotopic Ratio: [   3/   3.00060] =    100.000
Isotopic Ratio: [   3/   3.00070] =      1.000
Isotopic Ratio: [ 607/ 607.01214] =      1.000
Isotopic Ratio: [ 607/ 607.01314] =     20.000
MODEL:   5121./   2.97/  -0.27      mic = 1.0600             vt= 1.06 M/H=-0.27 
   6100.000     10.000      0.020      5.000
ALL abundances NOT listed below differ from solar by  -0.27 dex
element Li:  abundance =  3.43
element C :  abundance =  7.86
element N :  abundance =  8.16
element O :  abundance =  8.42
Isotopic Ratio: [   3/   3.00060] =    100.000
Isotopic Ratio: [   3/   3.00070] =      1.000
Isotopic Ratio: [ 607/ 607.01214] =      1.000
Isotopic Ratio: [ 607/ 607.01314] =     20.000
MODEL:   5121./   2.97/  -0.27      mic = 1.0600             vt= 1.06 M/H=-0.27 
   6100.000     10.000      0.020      5.000
ALL abundances NOT listed below differ from solar by  -0.27 dex
element Li:  abundance =  3.48
element C :  abundance =  7.86
element N :  abundance =  8.16
element O :  abundance =  8.42
Isotopic Ratio: [   3/   3.00060] =    100.000
Isotopic Ratio: [   3/   3.00070] =      1.000
Isotopic Ratio: [ 607/ 607.01214] =      1.000
Isotopic Ratio: [ 607/ 607.01314] =     20.000
MODEL:   5121./   2.97/  -0.27      mic = 1.0600             vt= 1.06 M/H=-0.27 
   6100.000     10.000      0.020      5.000
ALL abundances NOT listed below differ from solar by  -0.27 dex
element Li:  abundance =  3.53
element C :  abundance =  7.86
element N :  abundance =  8.16
element O :  abundance =  8.42
Isotopic Ratio: [   3/   3.00060] =    100.000
Isotopic Ratio: [   3/   3.00070] =      1.000
Isotopic Ratio: [ 607/ 607.01214] =      1.000
Isotopic Ratio: [ 607/ 607.01314] =     20.000
MODEL:   5121./   2.97/  -0.27      mic = 1.0600             vt= 1.06 M/H=-0.27 
   6100.000     10.000      0.020      5.000
ALL abundances NOT listed below differ from solar by  -0.27 dex
element Li:  abundance =  3.58
element C :  abundance =  7.86
element N :  abundance =  8.16
element O :  abundance =  8.42
Isotopic Ratio: [   3/   3.00060] =    100.000
Isotopic Ratio: [   3/   3.00070] =      1.000
Isotopic Ratio: [ 607/ 607.01214] =      1.000
Isotopic Ratio: [ 607/ 607.01314] =     20.000
MODEL:   5121./   2.97/  -0.27      mic = 1.0600             vt= 1.06 M/H=-0.27 
   6100.000     10.000      0.020      5.000

**Comment by madamow** [comment]
Usually this means that something wrong happened while compiling MOOG. Try to run Makefile and  check if it spits out errors

**Comment by wj198414** [comment]
I reinstall on my computer and it works. Thanks.
