### ISSUE TITLE
Feature Request: Example .par and linelist files for 'Blends' driver

### ISSUE THREAD

**Issue by kolecki4** [madamow/pymoogi#14]
I have been able to use the examples provided for Abfind, Synth, and Ewfind to get my own spectra and line lists to work with MOOG. However, having read the documentation [here](https://www.as.utexas.edu/~chris/codes/WRITEnov2019.pdf), I still have not been able to format my input files such that they make Blends function properly.

Is it possible for working example files to be provided for Blends?

**Comment by madamow** [comment]
Blends driver does not generate any plots nor works in the interactive mode. It just produces an output file.  I will push an example to the repository in a minute.

**Comment by kolecki4** [comment]
Thank you! I know it shouldn't produce output plots, but as of now even my summary_out file does not produce any useful information (Abundance = 999.99 for every input line feature). Perhaps the issue is that I am trying to process molecular blends of CO features, and missing an important nuance in that respect?

**Comment by madamow** [comment]
OK, I did the push. You will still get a lot of 999 after running example inputs. But if you want to know more about blends you need to ask on the MOOG's site.
