### ISSUE TITLE
importlib.metadata.PackageNotFoundError: pyMOOGi

### ISSUE THREAD

**Issue by eduardomatera** [madamow/pymoogi#15]
Hi. Thank you for this project.

I'm using 
. Debian Buster (10)
. Python 3.9.2
. python3-numpy 1:1.19.5-1
. python3-scipy 1.6.0-2
. python3-matplotlib 3.3.4-1

But when I execute:
pymoogi synth_example.par
I receive:

Traceback (most recent call last):
  File "/usr/bin/pymoogi", line 33, in <module>
    sys.exit(load_entry_point('pyMOOGi==1.0.0', 'console_scripts', 'pymoogi')())
  File "/usr/bin/pymoogi", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: pyMOOGi

What am I doing wrong?

Thanks in advance.

**Comment by Xarthisius** [comment]
How did you install `pymoogi`? It shouldn't have ended up in `/usr/bin/`...

Try this:
```
cd
sudo apt install -y gfortran virtualenv
git clone https://github.com/madamow/pymoogi/
cd pymoogi
virtualenv -p $(which python3.9) venv
. ./venv/bin/activate
pip install numpy scipy PyQt5 matplotlib
cd pymoogi/moog/
make
export MOOGPATH=$PWD
cd ../../
pip install .
hash -r
cd example
pymoogi synth_example.par
```
