### ISSUE TITLE
sh: 1: \rm: not found

### ISSUE THREAD

**Issue by debs122** [madamow/pymoogi#20]
Ma'am,
I have installed pymoogi and I am trying to run the examples. I could successfully run the synth_example.par. But I could not run the others. I am getting an error of sh: 1: \rm: not found. I have attached one picture for your reference.[
![Screenshot from 2022-08-09 09-36-51](https://user-images.githubusercontent.com/108093686/183562256-997bee70-4ae0-4b58-b017-49813c9b8b55.png)
](url)
Thanks and regards,
Debasish

**Comment by madamow** [comment]
The rm command is called in MOOG's Begin.f to remove a directory pymoogi doesn't use/create. It does not affect running Abfind driver. The screen you posted looks correct. You are asked to choose an element. Type 26 for Fe, hit enter, and you should be able to see a plot

**Comment by debs122** [comment]
Thank you ma'am. But for ewfind, blends, etc. I am not getting any output; only rm not found. 
![1](https://user-images.githubusercontent.com/108093686/183690801-73018dc5-f84f-4a0d-9d25-207eafe47b17.png)

And also, when I see the files, only for synth_example I am getting the file as executable(in green colour)
![2](https://user-images.githubusercontent.com/108093686/183691981-5691d9f2-60ab-4206-a25b-cc9f4072ee04.png)

**Comment by debs122** [comment]
Thank you ma'am. But, for ewfind, blends, etc. I am not getting any output and rm: not found is shown
![1i](https://user-images.githubusercontent.com/108093686/183693418-3e3d5d00-d3d9-4404-a913-1c9cf978f648.png)

Also when I see the files, I only  see synth_example as executable (in green colour). 
![2i](https://user-images.githubusercontent.com/108093686/183694134-8d818600-c69e-46e5-b272-c8168bff7b5f.png)

**Comment by madamow** [comment]
All par files are text files. They need to be readable, pymoogi doesn't care about them being executable.
Ewfind and blend drivers do not produce plots in pymoogi, just output files, so the behavior you see is correct. When you do: 
`ls -lrt` after running those drivers input files, you should notice new outputs.

**Comment by madamow** [comment]
I will add some prints in pymoogi to make an user aware that only output files, not plots are expected from blend and ewfind drivers.

**Comment by madamow** [comment]
I removed code from Begin.f that was checking the number of lines that could be printed in terminal as it is not needed for pymoogi. This solves the `\rm not found` confusion.

**Comment by debs122** [comment]
Thank you very much ma'am
