### ISSUE TITLE
error in compiling MOOG using make command

### ISSUE THREAD

**Issue by nagarajvernekar30** [madamow/pymoogi#21]
Hello, 

I tried installing Pymoogi as instructed. I was able to run the setup.py file for installing pymoogi but i was not able to compile MOOG due to which I am not able to use PyMOOGI. Everytime I run the make file within the pymoogi/pymoogi/moog folder, I get the following error. 

gfortran -O2 -g Abfind.o Batom.o Begin.o Blankstring.o Blends.o Bmolec.o Boxit.o Cdcalc.o Chabund.o Correl.o Crosscorr.o Curve.o Damping.o Discov.o Eqlib.o Estim.o Ewfind.o Ewweighted.o Fakeline.o Finish.o Gammabark.o Getasci.o Getcount.o Getnum.o Getsyns.o Infile.o Inlines.o Inmodel.o Invert.o Jexpint.o Lineinfo.o Lineabund.o Linlimit.o Minimax.o Molquery.o Moog.o Mydriver.o Nansi.o Nearly.o Number.o Obshead.o Oneline.o Opaccouls.o OpacHelium.o OpacHydrogen.o Opacit.o Opacmetals.o Opacscat.o Params.o Partfn.o Partnew.o Plotremember.o Prinfo.o Putasci.o Readobs.o Rinteg.o Setmols.o Smooth.o Stats.o Sunder.o Synspec.o Synth.o Tablepop.o Taukap.o Total.o Trudamp.o Ucalc.o Vargauss.o Vmacro.o Voigt.o Weedout.o Wavecalc.o Writenumber.o -static-libgfortran -o MOOG
/usr/bin/ld: warning: -z ignore ignored
/usr/bin/ld: warning: -z record ignored
/usr/bin/ld: .eh_frame_hdr refers to overlapping FDEs
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make: *** [Makefile:51: MOOG] Error 1

I do not understand why this is occurring. I would be thankful if you could point out the error.

**Comment by madamow** [comment]
Are you trying  it on Apple M1?

**Comment by nagarajvernekar30** [comment]
No, I am using Asus laptop with a intel process running on Ubuntu 22.04.

**Comment by madamow** [comment]
I am sorry, but it seems like an issue with libraries/settings specific to your laptop. My advice is to google as much as you can on that error, or maybe ask for your university IT helpdesk for help, or ask colleague who had a similar issue. It is not possible for me to debug it if it specific to your local libraries/settings.
