### ISSUE TITLE
Phoenix file type support

### ISSUE THREAD

**Issue by WLNORGREN** [madamow/pymoogi#8]
I am using pymoogi on the following file types, here is an example of what I am trying to do.  I am using the abfind algorithm with the following file types, the atmosphere is in phoenix format.  Here is the .par file I am using:

abfind
standard_out  'b'
summary_out   'bb'
model_in      'GJ3313.phx'
lines_in      'GJ3313.lin'
atmosphere    1
molecules     1
lines         1 
flux/int      0
plot          0
terminal      xterm
abundances    1    1
         29     0.0
damping       2

The name of this file is abgj3313.par, and the model atmosphere and line files are GJ3313.phx and GJ3313.lin, respectively.  When I run pymoogi abfind_example.par, there are no issues.  However, when I run pymoogi abgj3313.par , I get the following error message:

![Screenshot from 2021-04-02 10-59-39](https://user-images.githubusercontent.com/81774716/113432251-a5c3f500-93a2-11eb-848b-57478d3e5096.png)

In addition, I have modified Inmodel.f to support the phoenix model atmosphere type as follows:
[Inmodelf.txt](https://github.com/madamow/pymoogi/files/6250328/Inmodelf.txt)

Is it possible to use the phoenix model atmosphere type with pymoogi, or have I configured something incorrectly?

**Comment by madamow** [comment]
Form the quick look on your error, it seems like the problem is with the format of your output files. Could you send me an example of your output files? I can work on adjusting pymoogi to your case.

**Comment by WLNORGREN** [comment]
Hello Ms. Adamow,

Do you mean b and bb?

Thank you,

Wolf Norgren

**Comment by WLNORGREN** [comment]
Hello Ms. Adamow,

Thank you for helping me with this software!

Both me and my professor greatly appreciate pymoogi!

Thank you,

Wolf Norgren

**Comment by madamow** [comment]
Yes, b and bb. I will start from there. It is Friday today, so I will probably contact you back early next week :) 
Thank you for using pymoogi!

**Comment by WLNORGREN** [comment]
Hello Ms. Adamow,

I have changed b and bb to eqw1 and eqw2.  That seems to work!

Thank you for the help!

Is it OK if i contact you in the future about further pymoogi issues?

I am in an ongoing research project relating to stellar atmospheres.

Th

**Comment by WLNORGREN** [comment]
Thank you,

Wolf Norgren

**Comment by madamow** [comment]
I am happy that it worked. That is weird though that something depends on the name of the output files, so it is something I need to check. 
Please contact me about any issues with pymoogi, always happy to help!

**Comment by WLNORGREN** [comment]
Hello Ms. Adamow,

I had previously thought that changing the output names worked, but
instead, it seems like I keep seeing the data for the example star, instead
of the one I am trying to calculate the abundances for, when the output
files are set to eqw1 and eqw2.  What do you think I am doing wrong?  I am
still trying to use Phoenix model atmospheres.


Thank you,

Wolf Norgren

**Comment by madamow** [comment]
Ok, I will work on that. Could you please send me an example file with phoenix model?

**Comment by WLNORGREN** [comment]
Sure, here it is.

Hello Ms. Adamow,

Sorry for not getting back sooner.

The first screenshot is what I see when I first log in.

The second is the data for carbon for abfind_example.par
The third is the data for abGJ3313.par, a star I am trying to examine.


In both cases, I run pymoogi, and the output is identical.

Is there anything I haven't configured correctly?

I am using eqw1 and eqw2 for the output files in both cases.

**Comment by WLNORGREN** [comment]
Hello Ms. Adamow,

Here are the other two attachments.

Thank you,

Wolf Norgren

**Comment by madamow** [comment]
I do not see attached files. Could you send them directly to my email? madamow[at]icloud.com

**Comment by madamow** [comment]
My guess is the new output files are not created, old eqw1 and eqw2 are read in instead. But to recreate the error I need input files, at least the phoenix model file.

**Comment by WLNORGREN** [comment]
Hello Ms. Adamow,

Here are the input files I used.



Thank you,

Wolf Norgren

**Comment by kolecki4** [comment]
I'm trying to use PHOENIX model atmosphere files as well but I'm having some issues reading them in. What format are your PHOENIX model atmospheres in? If you don't mind, could you share an example?
