### ISSUE TITLE
Rank mismatch in argument ‘xnew’

### ISSUE THREAD

**Issue by jcrestani** [madamow/pymoogi#9]
Hi Monika! I have recently migrated from Linux to MacOS and I'm having problems installing pymoogi. Well, in fact the problem is, so far, Moog. I am getting several warnings of the form "Fortran 2018 deleted feature: DO termination statement which is not END DO or CONTINUE", and this error that stops the installation altogether:

OpacHydrogen.f:163:50:
  163 |          call linter (wfflog,fflog(1,itheta),nnnn,wavelog,fftlog,1)
      |                                                  1
Error: Rank mismatch in argument ‘xnew’ at (1) (rank-1 and scalar)
OpacHydrogen.f:169:47:
  169 |      .              maxwave = map1(wbf,bf,nnnn,wave,hminbf,1)
      |                                               1
Error: Rank mismatch in argument ‘xnew’ at (1) (rank-1 and scalar)
make: *** [OpacHydrogen.o] Error 1

The other .f files before this one compiled, with some of them showing the "Fortran 2018" warning above, but these errors on OpacHydrogen.f halt the installation altogether. 

Any clue what could be going on?

**Comment by madamow** [comment]
Hi!
I just updated pymoogi repo. OpacHydrogen.f file has some changes. Please pull from master, remove all *.o files and run `make` again.

**Comment by jcrestani** [comment]
Hi Monika,

Thank you! It works now (after a few more hours to get Python to work too...). See you again in two years when another update comes up and everything breaks once more!
